export const playersXgoalsParameters = new Set([
  "minimum_minutes",
  "minimum_shots",
  "minimum_key_passes",
  "player_id",
  "team_id",
  "season_name",
  "start_date",
  "end_date",
  "shot_pattern",
  "split_by_teams",
  "split_by_seasons",
  "split_by_games",
  "stage_name",
  "general_position",
]);
